services:
  frontend:
    build:
      context: ..
      dockerfile: frontend/Dockerfile
    ports:
      - "3000:80"
    environment:
      - NODE_ENV=production
      - VITE_API_BASE_URL=http://Server_IP
    restart: unless-stopped
    networks:
      - app-network

networks:
  app-network:
    driver: bridge 